-- MySQL Script generated by MySQL Workbench
-- lun 14 ene 2019 12:23:37 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GrandesAlmacenes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GrandesAlmacenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GrandesAlmacenes` DEFAULT CHARACTER SET utf8 ;
USE `GrandesAlmacenes` ;

-- -----------------------------------------------------
-- Table `GrandesAlmacenes`.`Cajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrandesAlmacenes`.`Cajeros` (
  `Cajero` INT NOT NULL AUTO_INCREMENT,
  `NomApels` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Cajero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrandesAlmacenes`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrandesAlmacenes`.`Productos` (
  `Producto` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrandesAlmacenes`.`Maquinas_Registradoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrandesAlmacenes`.`Maquinas_Registradoras` (
  `Maquina` INT NOT NULL,
  `Piso` INT NOT NULL,
  PRIMARY KEY (`Maquina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrandesAlmacenes`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrandesAlmacenes`.`Venta` (
  `Cajero` INT NOT NULL,
  `Maquina` INT NOT NULL,
  `Producto` INT NOT NULL,
  PRIMARY KEY (`Cajero`, `Maquina`, `Producto`),
  INDEX `fk_Venta_Maquinas_Registradoras1_idx` (`Maquina` ASC),
  INDEX `fk_Venta_Productos1_idx` (`Producto` ASC),
  CONSTRAINT `fk_Venta_Cajeros`
    FOREIGN KEY (`Cajero`)
    REFERENCES `GrandesAlmacenes`.`Cajeros` (`Cajero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venta_Maquinas_Registradoras1`
    FOREIGN KEY (`Maquina`)
    REFERENCES `GrandesAlmacenes`.`Maquinas_Registradoras` (`Maquina`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venta_Productos1`
    FOREIGN KEY (`Producto`)
    REFERENCES `GrandesAlmacenes`.`Productos` (`Producto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;